// The Final Travel Memory Jenkinsfile (Windows version)
pipeline {
    agent { label 'baskiparam' }

    environment {
        app_name = 'travel_memory'
    }

    parameters {
        booleanParam(name: 'RUN_TESTS', defaultValue: true, description: 'Check this to run unit tests.')
    }

    triggers {
        githubPush()
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/baskarp31/TravelMemory.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('TravelMemory-main\\backend') {
                    bat 'npm install'
                }
            }
        }

        stage('Run Tests') {
            when { expression { return params.RUN_TESTS } }
            steps {
                dir('TravelMemory-main\\backend') {
                    bat 'npm test'
                }
            }
        }

        stage('Login to AWS and Check S3 buckets') {
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', 
                  credentialsId: 'baskiawsjenkinsid']]) {
                    echo "checking AWS S3 bucket.."
                    bat "aws s3 ls"
                    echo "${env.app_name} running on AWS"
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline finished. Cleaning up."
            echo 'Installed and tested the application'
        }
        success {
            echo "Checked S3 Buckets"
        }
    }
}
