pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/baskarp31/TravelMemory.git'
            }
        }
        stage('Install') {
            steps {
                bat 'cd TravelMemory-main\\backend && npm install'
            }
        }
        stage('Build') {
            steps {
                bat 'cd TravelMemory-main\\backend && npm run build'
            }
        }
    }
}
